#!/bin/sh

# Iniciar sxhkd
pgrep -x sxhkd >/dev/null || sxhkd &

# Configuracion de los monitores
~/.config/screenlayout/monitors.sh &

sleep 1

# Workspaces
bspc monitor DisplayPort-0 -d I II III IV
bspc monitor HDMI-A-0 -d V VI VII VIII

# Configuración básica
bspc config border_width 0
bspc config window_gap 10
bspc config split_ratio 0.50
bspc config borderless_monocle true
bspc config gapless_monocle true
# bspc config padding_monocle    0

# Colores de borde
bspc config normal_border_color '#1f1f1f'
bspc config focused_border_color '#30302f'
bspc config presel_feedback_color '#512da8'

# Comportamiento
bspc config focus_follows_pointer true
bspc config pointer_modifier mod1
bspc config remove_disabled_monitors true

# Reglas de aplicaciones
bspc rule -a Gimp desktop='^VII' state=floating follow=on
bspc rule -a Chromium desktop='^II'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Iniciar componentes
~/.config/polybar/launch.sh --shapes &

picom --config ~/.config/picom/picom.conf &

feh --bg-fill ~/wallpapers/fondo-morado.png --bg-fill ~/wallpapers/fondo3.png &

# Configuración del mouse
xinput --set-prop 10 "libinput Accel Profile Enabled" 0, 1
xinput --set-prop 10 "libinput Accel Speed" -0.6
